/* =============================================================================
   Stage 7 · Step 01 — RBAC that scales: ACCESS roles + FUNCTIONAL roles
   -----------------------------------------------------------------------------
     ACCESS roles (AR_*)      hold privileges on objects   "can read MARTS.SALES"
     FUNCTIONAL roles (FR_*)  map to people / teams        "analyst", "marketing"
     FR roles are granted AR roles; users are granted FR roles. Never grant object
     privileges straight to a functional role or a user.

     FR_ANALYST           → AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_MARTS_OPS_READ, AR_WH_BI_USE
     FR_REGION_QA_MANAGER → AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_WH_BI_USE        (row policy: QA only)
     FR_MARKETING         → AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_MARTS_MARKETING_READ, AR_WH_BI_USE
     FR_DATA_SCIENTIST    → all MARTS read + AR_STAGING_READ + AR_WH_LAB_USE
     FR_ENGINEER          → RETAIL_ENGINEER (builds pipelines)
     GOVERNANCE_ADMIN     → owns the GOV database: tags, masking & row policies, mapping tables

   Plus: managed-access schemas, and moving Capstone 1's database-level future grants
   to schema level (a classic gotcha — see SECTION D).

   HOW TO RUN: worksheet → Run All (each section switches to the right system role).
   PREREQUISITE: dbt prod build done, so RETAIL_MARTS.CORE/SALES/MARKETING/OPS exist.
   ============================================================================= */

/* ---------------------------------------------------------------------------
   SECTION A — create the roles (USERADMIN)
   --------------------------------------------------------------------------- */
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS AR_MARTS_CORE_READ      COMMENT = 'SELECT on RETAIL_MARTS.CORE';
CREATE ROLE IF NOT EXISTS AR_MARTS_SALES_READ     COMMENT = 'SELECT on RETAIL_MARTS.SALES';
CREATE ROLE IF NOT EXISTS AR_MARTS_MARKETING_READ COMMENT = 'SELECT on RETAIL_MARTS.MARKETING';
CREATE ROLE IF NOT EXISTS AR_MARTS_OPS_READ       COMMENT = 'SELECT on RETAIL_MARTS.OPS';
CREATE ROLE IF NOT EXISTS AR_STAGING_READ         COMMENT = 'SELECT on all RETAIL_STAGING schemas';
CREATE ROLE IF NOT EXISTS AR_WH_BI_USE            COMMENT = 'USAGE on BI_WH';
CREATE ROLE IF NOT EXISTS AR_WH_LAB_USE           COMMENT = 'USAGE on LAB_WH';

CREATE ROLE IF NOT EXISTS FR_ANALYST            COMMENT = 'Business analysts (KE region via row policy)';
CREATE ROLE IF NOT EXISTS FR_REGION_QA_MANAGER  COMMENT = 'Qatar regional manager (QA only)';
CREATE ROLE IF NOT EXISTS FR_MARKETING          COMMENT = 'Marketing team: may see customer contact PII';
CREATE ROLE IF NOT EXISTS FR_DATA_SCIENTIST     COMMENT = 'Data science';
CREATE ROLE IF NOT EXISTS FR_ENGINEER           COMMENT = 'Data engineers';
CREATE ROLE IF NOT EXISTS GOVERNANCE_ADMIN      COMMENT = 'Owns tags, policies and governance mapping tables';

/* ---------------------------------------------------------------------------
   SECTION B — privileges on objects go to ACCESS roles (SECURITYADMIN has MANAGE GRANTS)
   --------------------------------------------------------------------------- */
USE ROLE SECURITYADMIN;

GRANT USAGE ON DATABASE RETAIL_MARTS TO ROLE AR_MARTS_CORE_READ;
GRANT USAGE ON DATABASE RETAIL_MARTS TO ROLE AR_MARTS_SALES_READ;
GRANT USAGE ON DATABASE RETAIL_MARTS TO ROLE AR_MARTS_MARKETING_READ;
GRANT USAGE ON DATABASE RETAIL_MARTS TO ROLE AR_MARTS_OPS_READ;

GRANT USAGE ON SCHEMA RETAIL_MARTS.CORE TO ROLE AR_MARTS_CORE_READ;
GRANT SELECT ON ALL TABLES    IN SCHEMA RETAIL_MARTS.CORE TO ROLE AR_MARTS_CORE_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_MARTS.CORE TO ROLE AR_MARTS_CORE_READ;
GRANT SELECT ON ALL VIEWS     IN SCHEMA RETAIL_MARTS.CORE TO ROLE AR_MARTS_CORE_READ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RETAIL_MARTS.CORE TO ROLE AR_MARTS_CORE_READ;

GRANT USAGE ON SCHEMA RETAIL_MARTS.SALES TO ROLE AR_MARTS_SALES_READ;
GRANT SELECT ON ALL TABLES    IN SCHEMA RETAIL_MARTS.SALES TO ROLE AR_MARTS_SALES_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_MARTS.SALES TO ROLE AR_MARTS_SALES_READ;
GRANT SELECT ON ALL VIEWS     IN SCHEMA RETAIL_MARTS.SALES TO ROLE AR_MARTS_SALES_READ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RETAIL_MARTS.SALES TO ROLE AR_MARTS_SALES_READ;

GRANT USAGE ON SCHEMA RETAIL_MARTS.MARKETING TO ROLE AR_MARTS_MARKETING_READ;
GRANT SELECT ON ALL TABLES    IN SCHEMA RETAIL_MARTS.MARKETING TO ROLE AR_MARTS_MARKETING_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_MARTS.MARKETING TO ROLE AR_MARTS_MARKETING_READ;
GRANT SELECT ON ALL VIEWS     IN SCHEMA RETAIL_MARTS.MARKETING TO ROLE AR_MARTS_MARKETING_READ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RETAIL_MARTS.MARKETING TO ROLE AR_MARTS_MARKETING_READ;

GRANT USAGE ON SCHEMA RETAIL_MARTS.OPS TO ROLE AR_MARTS_OPS_READ;
GRANT SELECT ON ALL TABLES    IN SCHEMA RETAIL_MARTS.OPS TO ROLE AR_MARTS_OPS_READ;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_MARTS.OPS TO ROLE AR_MARTS_OPS_READ;
GRANT SELECT ON ALL VIEWS     IN SCHEMA RETAIL_MARTS.OPS TO ROLE AR_MARTS_OPS_READ;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RETAIL_MARTS.OPS TO ROLE AR_MARTS_OPS_READ;
GRANT SELECT ON ALL DYNAMIC TABLES    IN SCHEMA RETAIL_MARTS.OPS TO ROLE AR_MARTS_OPS_READ;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA RETAIL_MARTS.OPS TO ROLE AR_MARTS_OPS_READ;

GRANT USAGE ON DATABASE RETAIL_STAGING TO ROLE AR_STAGING_READ;
GRANT USAGE ON ALL SCHEMAS IN DATABASE RETAIL_STAGING TO ROLE AR_STAGING_READ;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE RETAIL_STAGING TO ROLE AR_STAGING_READ;
GRANT SELECT ON ALL TABLES IN DATABASE RETAIL_STAGING TO ROLE AR_STAGING_READ;
GRANT SELECT ON ALL VIEWS  IN DATABASE RETAIL_STAGING TO ROLE AR_STAGING_READ;
GRANT SELECT ON FUTURE TABLES IN DATABASE RETAIL_STAGING TO ROLE AR_STAGING_READ;
GRANT SELECT ON FUTURE VIEWS  IN DATABASE RETAIL_STAGING TO ROLE AR_STAGING_READ;

GRANT USAGE ON WAREHOUSE BI_WH  TO ROLE AR_WH_BI_USE;
GRANT USAGE ON WAREHOUSE LAB_WH TO ROLE AR_WH_LAB_USE;

/* ---------------------------------------------------------------------------
   SECTION C — functional roles get access roles; everything rolls up to SYSADMIN
   --------------------------------------------------------------------------- */
GRANT ROLE AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_MARTS_OPS_READ, AR_WH_BI_USE TO ROLE FR_ANALYST;
GRANT ROLE AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_WH_BI_USE TO ROLE FR_REGION_QA_MANAGER;
GRANT ROLE AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_MARTS_MARKETING_READ, AR_WH_BI_USE TO ROLE FR_MARKETING;
GRANT ROLE AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_MARTS_MARKETING_READ, AR_MARTS_OPS_READ,
           AR_STAGING_READ, AR_WH_LAB_USE, AR_WH_BI_USE TO ROLE FR_DATA_SCIENTIST;
GRANT ROLE RETAIL_ENGINEER TO ROLE FR_ENGINEER;
GRANT ROLE AR_WH_LAB_USE TO ROLE GOVERNANCE_ADMIN;

GRANT ROLE FR_ANALYST, FR_REGION_QA_MANAGER, FR_MARKETING, FR_DATA_SCIENTIST, FR_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE GOVERNANCE_ADMIN TO ROLE SYSADMIN;

-- You personally get every functional role so you can test them (Step 07). Real users get one or two.
SET me = CURRENT_USER();
GRANT ROLE FR_ANALYST           TO USER IDENTIFIER($me);
GRANT ROLE FR_REGION_QA_MANAGER TO USER IDENTIFIER($me);
GRANT ROLE FR_MARKETING         TO USER IDENTIFIER($me);
GRANT ROLE FR_DATA_SCIENTIST    TO USER IDENTIFIER($me);
GRANT ROLE GOVERNANCE_ADMIN     TO USER IDENTIFIER($me);

/* ---------------------------------------------------------------------------
   SECTION D — the future-grants gotcha
   Capstone 1 created DATABASE-level future grants for RETAIL_ANALYST on RETAIL_MARTS.
   When a schema also has SCHEMA-level future grants (Section B), the schema-level ones WIN
   and the database-level ones are ignored for that schema. So RETAIL_ANALYST would silently
   stop getting new tables. Fix: make RETAIL_ANALYST a consumer of the access roles too,
   and remove the database-level future grants.
   --------------------------------------------------------------------------- */
GRANT ROLE AR_MARTS_CORE_READ, AR_MARTS_SALES_READ, AR_MARTS_OPS_READ TO ROLE RETAIL_ANALYST;
REVOKE SELECT ON FUTURE TABLES  IN DATABASE RETAIL_MARTS FROM ROLE RETAIL_ANALYST;
REVOKE SELECT ON FUTURE VIEWS   IN DATABASE RETAIL_MARTS FROM ROLE RETAIL_ANALYST;
REVOKE SELECT ON FUTURE DYNAMIC TABLES IN DATABASE RETAIL_MARTS FROM ROLE RETAIL_ANALYST;
SHOW FUTURE GRANTS IN SCHEMA RETAIL_MARTS.SALES;

/* ---------------------------------------------------------------------------
   SECTION E — GOV database owned by GOVERNANCE_ADMIN; centralised policy rights
   --------------------------------------------------------------------------- */
USE ROLE SYSADMIN;
CREATE DATABASE IF NOT EXISTS GOV COMMENT = 'Governance: tags, policies, mapping tables, data quality';
GRANT OWNERSHIP ON DATABASE GOV TO ROLE GOVERNANCE_ADMIN COPY CURRENT GRANTS;

USE ROLE ACCOUNTADMIN;
GRANT APPLY MASKING POLICY    ON ACCOUNT TO ROLE GOVERNANCE_ADMIN;
GRANT APPLY ROW ACCESS POLICY ON ACCOUNT TO ROLE GOVERNANCE_ADMIN;
GRANT APPLY TAG               ON ACCOUNT TO ROLE GOVERNANCE_ADMIN;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE GOVERNANCE_ADMIN;   -- ACCESS_HISTORY, TAG_REFERENCES

/* ---------------------------------------------------------------------------
   SECTION F — managed access schemas: only the schema owner / MANAGE GRANTS can grant,
   so an object owner can't quietly share a table with someone.
   --------------------------------------------------------------------------- */
USE ROLE RETAIL_ENGINEER;
ALTER SCHEMA RETAIL_MARTS.CORE      ENABLE MANAGED ACCESS;
ALTER SCHEMA RETAIL_MARTS.SALES     ENABLE MANAGED ACCESS;
ALTER SCHEMA RETAIL_MARTS.MARKETING ENABLE MANAGED ACCESS;
ALTER SCHEMA RETAIL_MARTS.OPS       ENABLE MANAGED ACCESS;

-- Look at the result
USE ROLE SECURITYADMIN;
SHOW GRANTS TO ROLE FR_MARKETING;
SHOW GRANTS OF ROLE AR_MARTS_SALES_READ;
